environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      ARCH: x86
      PYTHON: "C:\\Python36"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      ARCH: x86_64
      PYTHON: "C:\\Python36-x64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x86
      PYTHON: "C:\\Python36"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x86_64
      PYTHON: "C:\\Python36-x64"

# AppVeyor runs MSBuild by default, which fails if there is no project.
build: off

install:
  - ps: |
      $ErrorActionPreference = "Stop"
      ${env:PATH} = "${env:PYTHON};${env:PYTHON}\Scripts;${env:PATH}"
      python -m pip install --upgrade pip
      pip install --upgrade poetry
      poetry install

configuration:
  - MultiLine
  - OneLine

build_script:
  - ps: |
      $ErrorActionPreference = "Stop"
      Invoke-RestMethod https://raw.githubusercontent.com/thejohnfreeman/cmake-future/${env:APPVEYOR_REPO_COMMIT}/install.ps `
        | powershell -Command "`${env:commit} = '${env:APPVEYOR_REPO_COMMIT}'; powershell -Command -"
      mkdir build
      cd build
      cmake ..
      poetry run ctest --build-config Debug --verbose

for:
  - matrix:
      only:
        - configuration: MultiLine
    build_script:
      - ps: |
          $ErrorActionPreference = "Stop"
          md build
          cd build
          cmake ..
          cmake --build . --target install
          poetry run ctest --build-config Debug --verbose
