environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      ARCH: x86
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      ARCH: x86_64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x86
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x86_64

# AppVeyor runs MSBuild by default, which fails if there is no project.
build: off

install:
  - ps: |
      $ErrorActionPreference = "Stop"
      $env:PATH = "$env:PYTHON;$env:PYTHON\Scripts;$env:PATH"
      pip --disable-pip-version-check install pip pipenv
      pipenv install --dev

configuration:
  - MultiLine
  - OneLine

build_script:
  - ps: |
      $ErrorActionPreference = "Stop"
      Invoke-RestMethod https://raw.githubusercontent.com/thejohnfreeman/cmake-future/$env:APPVEYOR_REPO_COMMIT/install.ps `
        | powershell -Command "`$env:commit = '$env:APPVEYOR_REPO_COMMIT'; powershell -Command -"
      mkdir build
      cd build
      cmake ..
      pipenv run ctest --build-config Debug --verbose

for:
  - matrix:
      only:
        - configuration: MultiLine
    build_script:
      - ps: |
          $ErrorActionPreference = "Stop"
          md build
          cd build
          cmake ..
          cmake --build . --target install
          pipenv run ctest --build-config Debug --verbose
