# We need `language: python` to get Travis CI to supply pip3.
language: python
sudo: required

install:
  - pip3 install poetry
  - poetry install

multi-line: &multi-line
  - mkdir build
  - cd build
  - cmake ..
  # cmake is not on the sudo PATH.
  - sudo env "PATH=$PATH" cmake --build . --target install
  - poetry run ctest --verbose

one-line: &one-line
  - curl -L https://raw.githubusercontent.com/thejohnfreeman/cmake-future/${TRAVIS_COMMIT}/install.sh \
    | sudo env "PATH=$PATH" bash -s -- ${TRAVIS_COMMIT}
  - mkdir build
  - cd build
  - cmake ..
  - poetry run ctest --verbose

matrix:
  include:
    - os: linux
      dist: xenial
      script: *multi-line
    - os: osx
      # `xcode10.2` has Python 3.7.3.
      osx_image: xcode10.2
      # `language: python` tries to install Python, which fails on OSX.
      language: shell
      script: *multi-line
    - os: linux
      dist: xenial
      script: *one-line
    - os: osx
      osx_image: xcode10.2
      language: shell
      script: *one-line
