sudo: required

multi-line: &multi-line
  - mkdir build
  - cd build
  - cmake ..
  # cmake is not on the sudo PATH.
  - sudo env "PATH=$PATH" cmake --build . --target install
  - ctest -V

matrix:
  include:
    - os: linux
      dist: xenial
      script: *multi-line
    - os: linux
      dist: trusty
      script: *multi-line
    - os: osx
      script: *multi-line
