sudo: required

multi-line: &multi-line
  - mkdir build
  - cd build
  - cmake ..
  # cmake is not on the sudo PATH.
  - sudo env "PATH=$PATH" cmake --build . --target install
  - ctest -V

one-line: &one-line
  - curl -L https://raw.githubusercontent.com/thejohnfreeman/cmake-future/master/install.sh \
    | sudo env "PATH=$PATH" bash -s -- ${TRAVIS_COMMIT}
  - mkdir build
  - cd build
  - cmake ..
  - ctest --verbose

matrix:
  include:
    - os: linux
      dist: xenial
      script: *multi-line
    - os: linux
      dist: trusty
      script: *multi-line
    - os: osx
      script: *multi-line
    - os: linux
      dist: xenial
      script: *one-line
    - os: linux
      dist: trusty
      script: *one-line
    - os: osx
      script: *one-line
